### 2.3.1 정부호와 준정부호

양의 정부호(positive defien)와 준정부호(positive semi-definite)는 보통 대칭행렬에 대해서만 정의한다.

- 놈(norm)의 특징
$$ \alpha (스칼라) $$
$$ 
\lVert A \rVert \ge 0, 
\lVert \alpha A \rVert = \left\vert \alpha \right\vert \lVert A \rVert,
\lVert A + B \rVert \le \lVert A \rVert + \lVert B \rVert,
\lVert AB \rVert \le \lVert A \rVert \lVert B \rVert
$$

In [8]:
# norm() 

A = (np.arange(9)-4).reshape((3, 3))
A_norm = np.linalg.norm(A)
print("대각행렬 : \n", A)
print("A의 놈 : \n", A_norm)

대각행렬 : 
 [[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
A의 놈 : 
 7.745966692414834


- 대각합(trace)의 특징

$$ tr(cA) = c tr(A), tr(A^T) = tr(A), tr(A+B) = tr(A) + tr(B), tr(AB) = tr(BA), tr(ABC) = tr(BCA) = tr(CAB) $$

- 트레이스 트릭
이차형싱(quadratic form)의 미분을 구하는데 유용하게 사용된다.
$$ x^TAx = tr(x^TAx) = tr(Axx^T) = tr(xx^TA) $$

- 행렬 A의 놈에 제곱은 A의 전치행렬과 행렬 A의 곱에 대한 트레이시 값과 같다. 이를 통해 행렬 A가 벡터라면 벡터 A가 A의 전치행렬과 A의 곱과 같다. 

In [11]:
# trace()

np.trace(np.eye(3))

3.0