# 2. 넘파이(NumPy)로 공부하는 선형대수

## 2.2 백터와 행렬의 연산
대량의 데이터에 대한 계산을 간단한 수식으로 나타내기 ~~위해 연산이 필요하다.~~ 다만, 숫자의 사칙연산과 몇가지 다른점이 있다.  
- 벡터/행렬의 덧셈과 뺄셈, 스칼라와 벡터/행렬의 곱셈  

&nbsp;&nbsp;&nbsp;&nbsp;\*참고 : 브로드캐스팅

In [7]:
A = np.array([2,3,4,5,6])
A-10

array([-8, -7, -6, -5, -4])

### 2.2.1 벡터와 벡터의 곱셉
- 내적(정의/inner product) : ~~벡터와 벡터의 곱셈의 종류가운데 하나~~  
$$ x^Ty = c(스칼라)$$
- 특성 :  
    - 두벡터를 내적 ~~하기위해 필요한 조건~~  
        - 두 벡터의 차원(길이)가 같다.  
        - 앞의 벡터가 행벡터이고 뒤의 벡터가 열 벡터이여야 한다.

In [8]:
# dot(), @
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

a = x.T @ y  
b = np.dot(x.T, y)

a,b

(array([[32]]), array([[32]]))

- 특성(계속):
    - 벡터의 내적을 사용하여 데이터 분석하는 예시
        - 가중합(weighted sum)
        - 가중평균(weighted average) : ~~수업에 배정된 학점을 가중치로 반영하여 성적의 계산할 때 사용되는 것~~
        - 유사도(similarity)
        - 선형회귀 모형(linear regression model)
        - 제곱합(sum of squares) : $x^Tx$

### 2.2.2 행렬과 행렬의 곱셈

In [2]:
# @, dot()
A = np.array([[1, 2, 3], [4, 5, 6]]) # 2 X 3 matrix
B = np.array([[1, 2], [3, 4], [5, 6]]) # 3 X 2 matirx
C = A @ B # (2 X 2 matirix) = (2 X 3 matrix) X (3 x 2 matirx)
C  

array([[22, 28],
       [49, 64]])

- 특징:
    - 교환법칙과 분배법칙
$$ AB \ne BA $$
$$ A(B + C) = AB + AC $$
$$ (A + B)C = AC + BC $$  

  
    - 전치연사도 마찬가지로 덧셈/뺄셈에 대해 분배 법칙이 성립한다.
  
$$ (A + B)^T = A^T + B^T $$
  
    - 하지만 곱셉의 전치 연산이 분배되면 곱셈의 순서가 바뀐다.
  
$$ (AB)^T = B^TA^T$$
$$ (ABC)^T = C^TB^TA^T$$

In [3]:
# 교환법칙은 성립하지 않는다.
a = A@B
b = B@A
print (a,"\n not equal \n", b)

[[22 28]
 [49 64]] 
 not equal 
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [11]:
# 전치연산이 분배되면 곱셈의 순서가 바뀐다
AB_T=A@B
B_TA_T = B.T@A.T
print(AB_T.T, "\n equal \n", B_TA_T)

[[22 49]
 [28 64]] 
 equal 
 [[22 49]
 [28 64]]


$\bar{x} = {1\over N} 1_N 1^T_N X$

In [19]:
#아래 데이터로 위 행렬의 값을 계산하라. 이 행렬은 첫 번째 열의 값이 모두 같은 값으로 붓꽃의 꽃받침의 길이(sepal length)의 평균이고 두 번째 열의 값이 모두 같은 값으로 붓꽃의 꽃받침의 폭(sepal width)의 평균, 이런 식으로 계산된 행렬이다.
from sklearn.datasets import load_iris
X = load_iris().data

N = X.shape[0]
ones = np.ones(N).reshape(-1,1)
X_bar = ((ones@ones.T)@X)/N
X_bar[:5]

array([[5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333]])

- 특징(계속)
    - 연속된 행렬의 곱셈은 계산 순서를 임의의 순서로 해도 상관없다.

### 2.2.4 항등행렬의 곱셈
$$ AI = IA =A $$

### 2.2.5 행렬과 벡터의 곱
- 가장 널리 쓰이는 행렬과 벡터의 곱
    - 여러 개의 벡터에 대한 가중합 동시 계산
    - 잔차(residual)
$$ e_i = y_i - \hat{y}_i  = y_i - w^Tx_i $$ ~~**자주나온는 형태이니 암기하자**~~
    - 잔차 제곱합(RSS : Residual Sum of Squares) : 잔차의 크기~~를 도출하여 비교 등을 하려고 만들어 놓은 것(잔차의 제곱합과 제곱합은 다른개념이다)~~
$$
\begin{align}
\sum_{i=1}^{N} e_i^2 = \sum_{i=1}^{N} (y_i - w^Tx_i)^2 = e^Te =  (y - Xw)^T (y - Xw) 
\tag{2.2.83}
\end{align}
$$
    - 이차형식(Quadratic Form)
        - 어떤 벡터와 정방행렬이 '행벡터 x 정방행렬 x 열벡터'의 형식으로 되어 있는 것을 말함
$$ x^T A x = \sum_{i=1}^N \sum_{j=1}^N a_{i,j} x_i x_j$$

   ### 2.2.6 부분행렬
   - 특징 : 부분행렬(submatrix)를 이용하여 여러 방법으로 계산할 수 있다.
   
**1. 앞에 곱해지는 행렬을 행벡터로 나누어 계산해도 된다.**
$$
\begin{align}
AB 
=
\begin{bmatrix}
\boxed{\begin{matrix} \phantom{} & a_1^T & \phantom{} \end{matrix}} \\ 
\boxed{\begin{matrix} \phantom{} & a_2^T & \phantom{} \end{matrix}} \\ 
\end{bmatrix}
B
=
\begin{bmatrix}
\boxed{\begin{matrix} \phantom{} & a_1^TB & \phantom{} \end{matrix}} \\ 
\boxed{\begin{matrix} \phantom{} & a_2^TB & \phantom{} \end{matrix}} \\ 
\end{bmatrix} 
\tag{2.2.93}
\end{align}
$$
  
**2. 뒤에 곱해지는 행렬을 열벡터로 나누어 계산해도 된다.**
$$
\begin{align}
AB 
=
A
\begin{bmatrix}
\boxed{\begin{matrix} \phantom{\mathstrut} \\ b_1 \\ \phantom{\mathstrut} \end{matrix}} \!\!\!\! & 
\boxed{\begin{matrix} \phantom{\mathstrut} \\ b_2 \\ \phantom{\mathstrut} \end{matrix}}
\end{bmatrix}
=
\begin{bmatrix}
\boxed{\begin{matrix} \phantom{\mathstrut} \\ Ab_1 \\ \phantom{\mathstrut} \end{matrix}} \!\!\!\! &
\boxed{\begin{matrix} \phantom{\mathstrut} \\ Ab_2 \\ \phantom{\mathstrut} \end{matrix}}
\end{bmatrix}
\tag{2.2.96}
\end{align}
$$

**3. 앞에 곱해지는 행렬을 열벡터로, 뒤에 곱해지는 행렬을 행벡터로 나누어 스칼라처럼 계산해도 된다.**

$$
\begin{align}
AB 
=
\begin{bmatrix}
\boxed{\begin{matrix} \phantom{\mathstrut} \\ a_1 \\ \phantom{\mathstrut} \end{matrix}}  \!\!\!\!& 
\boxed{\begin{matrix} \phantom{\mathstrut} \\ a_2 \\ \phantom{\mathstrut} \end{matrix}}  \!
\end{bmatrix}
\begin{bmatrix}
\boxed{\begin{matrix} \phantom{} & b_1^T & \phantom{} \end{matrix}} \\ 
\boxed{\begin{matrix} \phantom{} & b_2^T & \phantom{} \end{matrix}} \\ 
\end{bmatrix}
=
\boxed{\begin{matrix} \phantom{\mathstrut} \\ a_1 \\ \phantom{\mathstrut} \end{matrix}} 
\boxed{\begin{matrix} \phantom{} & b_1^T & \phantom{} \end{matrix}} 
+
\boxed{\begin{matrix} \phantom{\mathstrut} \\ b_1 \\ \phantom{\mathstrut} \end{matrix}} 
\boxed{\begin{matrix} \phantom{} & b_2^T & \phantom{} \end{matrix}} 
\tag{2.2.98}
\end{align}
$$
